// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _cliquePartitioneR_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcpplique_gw_avg
IntegerVector rcpplique_gw_avg(NumericMatrix W_r);
RcppExport SEXP _cliquePartitioneR_rcpplique_gw_avg(SEXP W_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type W_r(W_rSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpplique_gw_avg(W_r));
    return rcpp_result_gen;
END_RCPP
}
// rcpplique_gw_basic
IntegerVector rcpplique_gw_basic(NumericMatrix W_r);
RcppExport SEXP _cliquePartitioneR_rcpplique_gw_basic(SEXP W_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type W_r(W_rSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpplique_gw_basic(W_r));
    return rcpp_result_gen;
END_RCPP
}
// rcpplique_gw_max
IntegerVector rcpplique_gw_max(NumericMatrix W_r);
RcppExport SEXP _cliquePartitioneR_rcpplique_gw_max(SEXP W_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type W_r(W_rSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpplique_gw_max(W_r));
    return rcpp_result_gen;
END_RCPP
}
// rcpplique_gw_outN
IntegerVector rcpplique_gw_outN(NumericMatrix W_r);
RcppExport SEXP _cliquePartitioneR_rcpplique_gw_outN(SEXP W_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type W_r(W_rSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpplique_gw_outN(W_r));
    return rcpp_result_gen;
END_RCPP
}
// rcpplique_gw_outW
IntegerVector rcpplique_gw_outW(NumericMatrix W_r);
RcppExport SEXP _cliquePartitioneR_rcpplique_gw_outW(SEXP W_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type W_r(W_rSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpplique_gw_outW(W_r));
    return rcpp_result_gen;
END_RCPP
}
// rcpplique_gw_sumPC
IntegerVector rcpplique_gw_sumPC(NumericMatrix W_r);
RcppExport SEXP _cliquePartitioneR_rcpplique_gw_sumPC(SEXP W_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type W_r(W_rSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpplique_gw_sumPC(W_r));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cliquePartitioneR_rcpp_hello_world", (DL_FUNC) &_cliquePartitioneR_rcpp_hello_world, 0},
    {"_cliquePartitioneR_rcpplique_gw_avg", (DL_FUNC) &_cliquePartitioneR_rcpplique_gw_avg, 1},
    {"_cliquePartitioneR_rcpplique_gw_basic", (DL_FUNC) &_cliquePartitioneR_rcpplique_gw_basic, 1},
    {"_cliquePartitioneR_rcpplique_gw_max", (DL_FUNC) &_cliquePartitioneR_rcpplique_gw_max, 1},
    {"_cliquePartitioneR_rcpplique_gw_outN", (DL_FUNC) &_cliquePartitioneR_rcpplique_gw_outN, 1},
    {"_cliquePartitioneR_rcpplique_gw_outW", (DL_FUNC) &_cliquePartitioneR_rcpplique_gw_outW, 1},
    {"_cliquePartitioneR_rcpplique_gw_sumPC", (DL_FUNC) &_cliquePartitioneR_rcpplique_gw_sumPC, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_cliquePartitioneR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
