# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_cliquePartitioneR_rcpp_hello_world`)
}

#' Rcpp Implementation of Basic Greedy Clique Partitioner
#'
#' This function assumes the matrix is symmetric and its diagonal is zeroed out
#' and performs no checks for correctness of the input.
#' Use \code{greedyCliquePartitioner()} for a robust version.
#'
#' @param W_r A numeric matrix, assumed to be symmetric with zeroes on its diagonal.
#' @return An integer vector encoding the clique membership of each node. Zeroes encode singletons.
#' @export 
rcpplique_gw_avg <- function(W_r) {
    .Call(`_cliquePartitioneR_rcpplique_gw_avg`, W_r)
}

#' Rcpp Implementation of Basic Greedy Clique Partitioner
#'
#' This function assumes the matrix is symmetric and its diagonal is zeroed out
#' and performs no checks for correctness of the input.
#' Use \code{greedyCliquePartitioner()} for a robust version.
#'
#' @param W_r A numeric matrix, assumed to be symmetric with zeroes on its diagonal.
#' @return An integer vector encoding the clique membership of each node. Zeroes encode singletons.
#' @export 
rcpplique_gw_basic <- function(W_r) {
    .Call(`_cliquePartitioneR_rcpplique_gw_basic`, W_r)
}

#' Rcpp Implementation of Basic Greedy Clique Partitioner
#'
#' This function assumes the matrix is symmetric and its diagonal is zeroed out
#' and performs no checks for correctness of the input.
#' Use \code{greedyCliquePartitioner()} for a robust version.
#'
#' @param W_r A numeric matrix, assumed to be symmetric with zeroes on its diagonal.
#' @return An integer vector encoding the clique membership of each node. Zeroes encode singletons.
#' @export 
rcpplique_gw_max <- function(W_r) {
    .Call(`_cliquePartitioneR_rcpplique_gw_max`, W_r)
}

#' Rcpp Implementation of Basic Greedy Clique Partitioner
#'
#' This function assumes the matrix is symmetric and its diagonal is zeroed out
#' and performs no checks for correctness of the input.
#' Use \code{greedyCliquePartitioner()} for a robust version.
#'
#' @param W_r A numeric matrix, assumed to be symmetric with zeroes on its diagonal.
#' @return An integer vector encoding the clique membership of each node. Zeroes encode singletons.
#' @export 
rcpplique_gw_outN <- function(W_r) {
    .Call(`_cliquePartitioneR_rcpplique_gw_outN`, W_r)
}

#' Rcpp Implementation of Basic Greedy Clique Partitioner
#'
#' This function assumes the matrix is symmetric and its diagonal is zeroed out
#' and performs no checks for correctness of the input.
#' Use \code{greedyCliquePartitioner()} for a robust version.
#'
#' @param W_r A numeric matrix, assumed to be symmetric with zeroes on its diagonal.
#' @return An integer vector encoding the clique membership of each node. Zeroes encode singletons.
#' @export 
rcpplique_gw_outW <- function(W_r) {
    .Call(`_cliquePartitioneR_rcpplique_gw_outW`, W_r)
}

#' Rcpp Implementation of Basic Greedy Clique Partitioner
#'
#' This function assumes the matrix is symmetric and its diagonal is zeroed out
#' and performs no checks for correctness of the input.
#' Use \code{greedyCliquePartitioner()} for a robust version.
#'
#' @param W_r A numeric matrix, assumed to be symmetric with zeroes on its diagonal.
#' @return An integer vector encoding the clique membership of each node. Zeroes encode singletons.
#' @export 
rcpplique_gw_sumPC <- function(W_r) {
    .Call(`_cliquePartitioneR_rcpplique_gw_sumPC`, W_r)
}

